config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root "restaurants#index"

  resources :restaurants, only: [:index, :show] do

    collection do 
      get :feeds
      get :ranking
    end 
    
    member do 
      get :dashboard

      post :favourite
      post :unfavourite
      
      post :like
      delete :unlike
    end

    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :create, :index]

  resources :categories, only: :show

  resources :followships, only: [:create, :destroy]

  resources :friendships, only: [:create, :destroy]

  namespace :admin do
  	resources :restaurants
  	resources :categories
  	root "restaurants#index"
  end


end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	mount_uploader :image, PhotoUploader
	validates_presence_of :name

	belongs_to :category, optional: true
	delegate :name, to: :category, prefix: true, allow_nil: true

	#Comment Implementation
	has_many :comments, dependent: :destroy

	#Favourite Implementation
	has_many :favourites, dependent: :destroy
	has_many :favourite_users, through: :favourites, source: :user

	#Like Implementation
	has_many :likes, dependent: :destroy
	has_many :liked_users, through: :likes, source: :user

	def is_favourite?(user)
		self.favourite_users.include?(user)
	end

	def is_liked?(user)
		self.liked_users.include?(user)
	end
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController

	before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

	def index 
		@restaurants = Restaurant.page(params[:page]).per(10)
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = Restaurant.new(restaurant_params)
		if @restaurant.save
			redirect_to admin_restaurants_path
			flash[:notice] = "restaurant was successfully created"
		else
			render :new
			flash[:alert] = "restaurant cannot be created"
		end
	end

	def show
	end

	def edit
	end

	def update
		if @restaurant.update(restaurant_params)
			redirect_to admin_restaurant_path(@restaurant)
			flash[:notice] = "restaurant was successfully created"
		else
			render :edit
			flash[:alert] = "restaurant cannot be created"
		end
	end

	def destroy
		@restaurant.destroy
		redirect_to action: 'index'
		flash[:alert] = "restaurant #{@restaurant.name} was deleted"
	end


	private
	def restaurant_params
		params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
	end

	def set_restaurant
		@restaurant = Restaurant.find(params[:id])
	end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	before_action :set_user, only: [:show, :dashboard, :favourite, :unfavourite, :like, :unlike]

	def index
		@restaurants = Restaurant.page(params[:page]).per(9)
		@categories = Category.all
	end
	
	def show
		@comment = Comment.new
	end

	def feeds
		@recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
		@recent_comments= Comment.order(created_at: :desc).limit(10)
	end

	def dashboard
	end

	def favourite
		Favourite.create(restaurant: @restaurant, user: current_user)
		redirect_back(fallback_location: root_path)
	end

	def unfavourite
		Favourite.where(restaurant: @restaurant, user: current_user).destroy_all
		redirect_back(fallback_location: root_path)
	end

	def like
		Like.create(restaurant: @restaurant, user: current_user)
		redirect_back(fallback_location: root_path)
	end

	def unlike
		Like.where(restaurant: @restaurant, user: current_user).destroy_all
		redirect_back(fallback_location: root_path)
	end

	def ranking
		@restaurants = Restaurant.all.order('favourites_count desc').limit(10)
	end

	private
	def set_user
		@restaurant = Restaurant.find(params[:id])
	end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/restaurants/_form.html.erb
<div class="container">
  <div class="row">
    <% if @restaurant.errors.any? %>
      <h4>We have some errors here !</h2>
      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <hr>
    <%end%>
    <%= form_for  [:admin, @restaurant] do |f| %>
      <div class="form-group">
        <%= f.label :category, "Category"%>
        <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: true}, {class: "form-control"}%>
      </div>

      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :tel, "Tel" %>
        <%= f.text_field :tel, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :address, "Address" %>
        <%= f.text_field :address,class: "form-control" %>
      </div>
     
      <div class="form-group">
        <%= f.label :opening_hours, "Opening Hours" %>
        <%= f.text_field :opening_hours, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :description, "Description" %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :image, "Photo" %>
        <%= image_tag @restaurant.image, width: '300px' if @restaurant.image? %>
        <%= f.file_field :image %>
      </div>
      
      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/restaurants/edit.html.erb
<%= render partial: "form" %>

app/views/admin/restaurants/index.html.erb
<div class="container">
	<div class="panel panel-default panel-table">
		<div class="panel-heading">
			<div class="row">
				<div class="col col-xs-6">
					<h3 class="panel-title">餐廳列表</h3>
					<div>
					  <%= link_to 'Restaurant', admin_restaurants_path %> |
					  <%= link_to 'Categories', admin_categories_path %>
					</div>
				</div>
			</div>
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col col-xs-6">
					<button type="button" class="btn btn-md btn-create"><%= link_to '新增餐廳', new_admin_restaurant_path%></button>
				</div>
			</div>
			<br>
			<div class="table-responsive">
				<table class="table table-bordered">
					<thead>
						<tr>
							<th>#</th>
							<th>Name</th>
							<th>Category</th>
							<th>Tel</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						<% @restaurants.each do |restaurant| %>
						<tr>
							<th scope = "row"><%= restaurant.id%></th>
							<td><%= restaurant.name%></td>
							<td><%= restaurant.category_name%></td>
							<td><%= restaurant.tel%></td>
							<td>
								<%= link_to 'Show', admin_restaurant_path(restaurant) %>
								<%= link_to 'Edit', edit_admin_restaurant_path(restaurant) %>
								<%= link_to 'Delete', admin_restaurant_path(restaurant), method: :delete, data: {confirm: "Are you sure?"} %>
							</td>
						</tr>
						<% end %>
					</tbody>	
				</table>
			</div>
		</div>
		<div class="panel-footer">
			<%= paginate @restaurants, :theme => 'twitter-bootstrap-4'%>
		</div>
	</div>
</div>

app/views/admin/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <h2>We have some errors here !</h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for  [:admin, @restaurant] do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  
  <%= f.label :tel, "Tel" %>
  <%= f.text_field :tel %>
  
  <%= f.label :address, "Address" %>
  <%= f.text_field :address %>

  <%= f.label :opening_hours, "Opening Hours" %>
  <%= f.text_field :opening_hours %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/admin/restaurants/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1><%= @restaurant.name%></h1>
		</div>
		<div class="col-md-4">
			<%= @restaurant.category.name%>
			<%= image_tag @restaurant.image, width: '350px'%>
			<div class="well">
				<ul class="list-unstyled">
					<li><strong>Opening Hours: </strong><%= @restaurant.opening_hours%></li>
					<li><strong>Tel: </strong><%= @restaurant.tel%></li>
					<li><strong>Address: </strong><%= @restaurant.address%></li>
				</ul>
			</div>
		</div>
		<div class="col-md-8">
			<%= simple_format @restaurant.description%>
		</div>
		<div class="clearfix"></div>
		<div class="col-md-12"><%= link_to 'Back', admin_restaurants_path %></div>
	</div>
</div>