config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root "restaurants#index"

  resources :restaurants, only: [:index, :show] do

    collection do 
      get :feeds
      get :ranking
    end 
    
    member do 
      get :dashboard

      post :favourite
      post :unfavourite
      
      post :like
      delete :unlike
    end

    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :create, :index]

  resources :categories, only: :show

  resources :followships, only: [:create, :destroy]

  resources :friendships, only: [:create, :destroy]

  namespace :admin do
  	resources :restaurants
  	resources :categories
  	root "restaurants#index"
  end


end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	mount_uploader :image, PhotoUploader
	validates_presence_of :name

	belongs_to :category, optional: true
	delegate :name, to: :category, prefix: true, allow_nil: true

	#Comment Implementation
	has_many :comments, dependent: :destroy

	#Favourite Implementation
	has_many :favourites, dependent: :destroy
	has_many :favourite_users, through: :favourites, source: :user

	#Like Implementation
	has_many :likes, dependent: :destroy
	has_many :liked_users, through: :likes, source: :user

	def is_favourite?(user)
		self.favourite_users.include?(user)
	end

	def is_liked?(user)
		self.liked_users.include?(user)
	end
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController

	before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

	def index 
		@restaurants = Restaurant.page(params[:page]).per(10)
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = Restaurant.new(restaurant_params)
		if @restaurant.save
			redirect_to admin_restaurants_path
			flash[:notice] = "restaurant was successfully created"
		else
			render :new
			flash[:alert] = "restaurant cannot be created"
		end
	end

	def show
	end

	def edit
	end

	def update
		if @restaurant.update(restaurant_params)
			redirect_to admin_restaurant_path(@restaurant)
			flash[:notice] = "restaurant was successfully created"
		else
			render :edit
			flash[:alert] = "restaurant cannot be created"
		end
	end

	def destroy
		@restaurant.destroy
		redirect_to action: 'index'
		flash[:alert] = "restaurant #{@restaurant.name} was deleted"
	end


	private
	def restaurant_params
		params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
	end

	def set_restaurant
		@restaurant = Restaurant.find(params[:id])
	end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	before_action :set_user, only: [:show, :dashboard, :favourite, :unfavourite, :like, :unlike]

	def index
		@restaurants = Restaurant.page(params[:page]).per(9)
		@categories = Category.all
	end
	
	def show
		@comment = Comment.new
	end

	def feeds
		@recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
		@recent_comments= Comment.order(created_at: :desc).limit(10)
	end

	def dashboard
	end

	def favourite
		Favourite.create(restaurant: @restaurant, user: current_user)
		redirect_back(fallback_location: root_path)
	end

	def unfavourite
		Favourite.where(restaurant: @restaurant, user: current_user).destroy_all
		redirect_back(fallback_location: root_path)
	end

	def like
		Like.create(restaurant: @restaurant, user: current_user)
		redirect_back(fallback_location: root_path)
	end

	def unlike
		Like.where(restaurant: @restaurant, user: current_user).destroy_all
		redirect_back(fallback_location: root_path)
	end

	def ranking
		@restaurants = Restaurant.all.order('favourites_count desc').limit(10)
	end

	private
	def set_user
		@restaurant = Restaurant.find(params[:id])
	end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/dashboard.html.erb
<h1><%= @restaurant.name %>'s Dashboard</h1>
<hr>
<ul>
  <li>有 <%= @restaurant.comments.count %> 筆評論</li>
  <li>這家餐廳的平均價位為 $XXX</li>
  <li>有 XX 人收藏這家餐廳</li>
</ul>

app/views/restaurants/feeds.html.erb
<div class="container">
	<%= render partial: "shared/navbar"%>
	<div class="nav-page">
		<br>
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<div class="col-md-6">
					<div class="panel panel-default">
						<div class="panel-heading">最新餐廳</div>
						<div class="panel-body">

						  <% @recent_restaurants.each do |restaurant| %>
						  <h4><%= link_to restaurant.name, restaurant_path(restaurant) %></h4>
						  <p><%= restaurant.category.name %></p>
						  <p><%= restaurant.description %></p>
						  <hr>
						  <% end %>
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="panel panel-default">
						<div class="panel-heading">最新評論</div>
						<div class="panel-body">
						  <% @recent_comments.each do |comment| %>
						  <h4><%= link_to comment.restaurant.name, restaurant_path(comment.restaurant) %></h4>
						  <p><%= comment.content %></p>
						  <p>by <%= link_to comment.user.name, user_path(comment.user) %></p>
						  <hr>
						  <% end %>
						</div>
					</div>
				</div>			
			</div>
		</div>
		
		
		
	</div>
</div>

app/views/restaurants/index.html.erb
<div class="container">
	<%= render partial: "shared/navbar"%>
	<div class="nav-page">
		<br>
		<div class="nav-center">
			<ul class="nav nav-pills">
				<li role="presentation" class="active"><%= link_to '全部餐廳', root_path %></li>
				<% @categories.each do |category| %>
				<li role="presentation"><%= link_to category.name, category_path(category)%></li>
				<% end %>
			</ul>
		</div>
	<%= render partial: "shared/restaurant_list" %>
	</div>
	

</div>

app/views/restaurants/ranking.html.erb
<div class="container">
	<%= render partial: "shared/navbar"%>
	<div class="nav-page">
		<br>
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<h3>Top 10 人氣餐廳</h3>
				<% @restaurants.each do |restaurant| %>
					<div class="row">
						<div class="col-md-4">
							<%= image_tag "/fake_images/00#{rand(0..9)}.jpg", size: "300x200" %>
							<%#= image_tag restaurant.image, size: "300x200" %>
						</div>
						<div class="col-md-8">
							<h4><%= restaurant.name%></h4>
							<h4>收藏數<%= restaurant.favourites_count%></h4>
							<p><%= truncate(restaurant.description, length: 150)%></p>
							<%= link_to 'Show', restaurant_path(restaurant), class: "btn btn-primary"%>
							<%= render partial: "shared/favourite.html.erb", locals: {restaurant: restaurant}%>
						</div>
					</div>
					<br>
				<%end%>
			</div>
			
		</div>
		
	</div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1><%= @restaurant.name%></h1>
		</div>
		<div class="col-md-4">
			<%= @restaurant.category.name%>
			<%= image_tag @restaurant.image, width: '350px'%>
			<div class="well">
				<ul class="list-unstyled">
					<li><strong>Opening Hours: </strong><%= @restaurant.opening_hours%></li>
					<li><strong>Tel: </strong><%= @restaurant.tel%></li>
					<li><strong>Address: </strong><%= @restaurant.address%></li>
				</ul>
			</div>
		</div>
		<div class="col-md-8">
			<%= simple_format @restaurant.description%>
			<%= link_to "Dashboard", dashboard_restaurant_path(@restaurant.id),class: "btn btn-primary"%>
			<%= render partial: "shared/favourite.html.erb", locals: {restaurant: @restaurant}%>
			<%= render partial: "shared/like.html.erb", locals: {restaurant: @restaurant}%>
		</div>
		<div class="clearfix"></div>
		<div class="col-md-12"><%= link_to 'Back', restaurants_path %></div>
		
		<% @restaurant.comments.each do |comment| %>
		<div class="col-md-12">
			<h4><%= comment.user.name %></h4>
			<p><%= simple_format comment.content %></p>
			<p class="text-muted"><em><%= time_ago_in_words(comment.created_at)%></em></p>
			<% if current_user.admin? %>
   				<%= link_to "Delete", restaurant_comment_path(@restaurant, comment), method: :delete %>
			<% end %>
			<hr>
		</div>
		<% end %>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<%= form_for [@restaurant, @comment] do |f| %>
				<div class="form-group">
					<%= f.text_area :content, placeholder: "留個言吧", class: "form-control"%>
				</div>
				<div class="form-group">
					<%= f.submit class: "btn btn-primary"%>
					<%= f.button "Cancel", type: :reset, class: "btn btn-default"%>
				</div>
			<% end %>
		</div>
	</div>
</div>