config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root "restaurants#index"

  resources :restaurants, only: [:index, :show] do

    collection do 
      get :feeds
      get :ranking
    end 
    
    member do 
      get :dashboard

      post :favourite
      post :unfavourite
      
      post :like
      delete :unlike
    end

    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :create, :index]

  resources :categories, only: :show

  resources :followships, only: [:create, :destroy]

  resources :friendships, only: [:create, :destroy]

  namespace :admin do
  	resources :restaurants
  	resources :categories
  	root "restaurants#index"
  end


end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true, uniqueness: true
	has_many :restaurants, dependent: :restrict_with_error
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

	before_action :set_category, only: [:update, :destroy]

	def index
		@categories = Category.all
		if params[:id]
			@category = Category.find(params[:id])
		else
			@category = Category.new
		end
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:notice] = "category was successfully created"
			redirect_to admin_categories_path
		else
			flash[:alert] = "category must have a unique name"
			@categories = Category.all
			render :index
		end
	end

	def update
		if @category.update(category_params)
			redirect_to admin_categories_path
			flash[:notice] = "category #{@category.name} was successfully updated"
		else
			flash[:alert] = "category must have a unique name"
			@categories = Category.all
			render :index
		end
	end

	def destroy
		if @category.destroy
			flash[:notice] = "category #{@category.name} was successfully deleted"
			redirect_to admin_categories_path
		else
			flash[:alert] = "category #{@category.name} cannot be deleted"
			redirect_to admin_categories_path
		end

	end


	private

	def category_params
		params.require(:category).permit(:name)
	end

	def set_category
		@category = Category.find(params[:id])
	end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show
		@categories = Category.all
		@category = Category.find(params[:id])
		@restaurants = @category.restaurants.page(params[:page]).per(9)
	end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/index.html.erb
<div class="container">
	<div class="panel panel-default panel-table">
		<div class="panel-heading">
			<div class="row">
				<div class="col col-xs-6">
					<h3 class="panel-title">分類列表</h3>
					<div>
					  <%= link_to 'Restaurant', admin_restaurants_path %> |
					  <%= link_to 'Categories', admin_categories_path %>
					</div>
				</div>
			</div>
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col col-xs-6">
					<div class="form-inline">
					<%= form_for [:admin, @category] do |f| %>
						<div class = "form-group">
							<%= f.text_field :name, placeholder: "Category Name", class: "form-control" %>
						</div>
						<%= f.submit class: "btn btn-primary"%>
					<% end %>	
					</div>
					<% if @category.errors.any? %>
							<%= @category.errors.full_messages.to_sentence %>
					<% end %>
				</div>
			</div>
			<br>
			<div class="table-responsive">
				<table class="table table-bordered">
					<thead>
						<tr>
							<th>Category Name</th>
							<th>#</th>
						</tr>
					</thead>
					<tbody>
						<% @categories.each do |category| %>
						<tr>
							<td><%= category.name%></td>
							<td><%= link_to 'Edit', admin_categories_path(id: category.id)%> <%= link_to 'Delete', admin_category_path(category), method: :delete, data: { confirm: "Are you sure?"}%></td>
						</tr>
						<% end %>
					</tbody>	
				</table>
			</div>
		</div>
	</div>
</div>