config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root "restaurants#index"

  resources :restaurants, only: [:index, :show] do

    collection do 
      get :feeds
      get :ranking
    end 
    
    member do 
      get :dashboard

      post :favourite
      post :unfavourite
      
      post :like
      delete :unlike
    end

    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :create, :index]

  resources :categories, only: :show

  resources :followships, only: [:create, :destroy]

  resources :friendships, only: [:create, :destroy]

  namespace :admin do
  	resources :restaurants
  	resources :categories
  	root "restaurants#index"
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true, uniqueness: true
	has_many :restaurants, dependent: :restrict_with_error
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :user
	belongs_to :restaurant

	validates_presence_of :content
end

app/models/favourite.rb
class Favourite < ApplicationRecord
	belongs_to :user
	belongs_to :restaurant, counter_cache: true
end

app/models/followship.rb
class Followship < ApplicationRecord
	belongs_to :user
	belongs_to :following, class_name: "User"
	
	validates :following_id, uniqueness: {scope: :user_id}
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, class_name: "User"

	validates :friend_id, uniqueness: {scope: :user_id}
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	mount_uploader :image, PhotoUploader
	validates_presence_of :name

	belongs_to :category, optional: true
	delegate :name, to: :category, prefix: true, allow_nil: true

	#Comment Implementation
	has_many :comments, dependent: :destroy

	#Favourite Implementation
	has_many :favourites, dependent: :destroy
	has_many :favourite_users, through: :favourites, source: :user

	#Like Implementation
	has_many :likes, dependent: :destroy
	has_many :liked_users, through: :likes, source: :user

	def is_favourite?(user)
		self.favourite_users.include?(user)
	end

	def is_liked?(user)
		self.liked_users.include?(user)
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name, :email

  #For Comment implementation
  has_many :comments, dependent: :restrict_with_error
  has_many :commented_restaurants, through: :comments, source: :restaurant

  #For Favourite Restaurant Implementation
  has_many :favourites, dependent: :destroy
  has_many :favourite_restaurants, through: :favourites, source: :restaurant

  #For Liked Restaurant Implementation
  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  #Followships
  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user

  #Friendships
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :inverse_friends, class_name: "Friendship", foreign_key: "friend_id"
  has_many :frienders, through: :inverse_friends, source: :user

  mount_uploader :avatar, UserAvatarUploader

  def admin?
  	self.role == "admin"
  end

  def following?(user)
    self.followings.include?(user)
  end

  def friend_of?(user)
    self.friends.include?(user)
  end

  def all_friends
    (self.friends + self.frienders).uniq
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
 

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show
		@categories = Category.all
		@category = Category.find(params[:id])
		@restaurants = @category.restaurants.page(params[:page]).per(9)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
		@comment = @restaurant.comments.build(comment_params)
		@comment.user = current_user
		@comment.save!
		redirect_to restaurant_path(@restaurant)
	end

	#can a user submit comments more than 1 time to the same restaurant?

	def destroy
		@restaurant = Restaurant.find(params[:restaurant_id])
		@comment = Comment.find(params[:id])

		if current_user.admin?
			@comment.destroy
			redirect_to restaurant_path(@restaurant)
		end
	end


	private

	def comment_params
		params.require(:comment).permit(:content)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :update, :edit]

	def index
		@users = User.all
	end

	def show
		@commented_restaurants = @user.commented_restaurants.uniq
		@favourite_restaurants = @user.favourite_restaurants.uniq
		@followings = @user.followings
		@followers = @user.followers
		@all_friends = @user.all_friends
	end

	def edit
	end

	def update
		if current_user != @user
			redirect_to user_path(current_user)
			flash[:alert] = "you cannot edit someone else profile"
		end

		if @user.update!(user_params)
			redirect_to user_path(@user)
			flash[:notice] = "user was successfully updated"
		else
			redirect_to user_path(@user)
			flash[:alert] = "user cannot be updated because you missed some fields"
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :intro, :avatar)
	end

	def set_user
		@user = User.find(params[:id])
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_nav_page?(test_path)
		'active' if request.path == test_path
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<nav class="navbar navbar-default">
  		<div class="container-fluid">
   		<!-- Brand and toggle get grouped for better mobile display -->
    		<div class="navbar-header"><%= link_to "餐廳評論網", root_path, class: "navbar-brand"%></div> 
    		<div class="collapse navbar-collapse">
    			<ul class="nav navbar-nav navbar-right">
				     <% if current_user %>
				     	<li class="navbar-text">Signed in as <%= current_user.email %></li>
				     	<li class="dropdown">
				     		<a class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Dropdown  <span class="caret"></span></a>
				     		<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
				     			<% if current_user.admin? and not current_page?(admin_restaurants_path)  %>
								<li class="dropdown-item"><%= link_to 'Admin後台', admin_restaurants_path %></li>
						     	<%end%>
						     	<% if current_page?(admin_restaurants_path)  %>
								<li class="dropdown-item"><%= link_to 'Admin前台', root_path %></li>
						     	<%end%>
						     	<li class="dropdown-item"><%= link_to('Profile', user_path(current_user.id))%></li>
				             	<li class="dropdown-item"><%= link_to('登出', destroy_user_session_path, method: :delete) %></li>
				             	<li class="dropdown-item"><%= link_to('修改密碼', edit_user_registration_path) %></li>
				     		</ul>
				     	</li>
				     	
		             <% else %>
			             <ul class="nav navbar-nav">
			             	<li><%= link_to('註冊', new_user_registration_path) %></li>
			             	<li><%= link_to('登入', new_user_session_path) %></li>
			             </ul>
		             <% end %>
				</ul>

    		</div>
		    
		</div>
	</nav>
	
	<% if flash[:notice]%>
	<div class="container">
		<div class= "row">
			<div class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">
						&times;
					</span>
				</button>
				<%=  notice %></div>
		</div>
	</div>
	<%end%>

	<% if flash[:alert]%>
	<div class="container">
		<div class= "row">
			<div class="alert alert-danger">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">
						&times;
					</span>
				</button>
				<%=  alert %>
			</div>
		</div>
	</div>
	<%end%>

    <%= yield %>
  </body>
</html>

app/views/shared/_favourite.html.erb
<% if not restaurant.is_favourite?(current_user)%>
	<%= link_to favourite_restaurant_path(restaurant), method: :post, :id => "favourite-heart", :class => "btn btn-outline-primary" do %>
		<span class="glyphicon glyphicon-heart-empty"></span>
	<%end%>
<%else%>
	<%= link_to unfavourite_restaurant_path(restaurant), method: :post, :id => "favourite-heart", :class => "btn btn-outline-primary" do %>
		<span class="glyphicon glyphicon-heart"></span>
	<%end%>
<%end%>

app/views/shared/_follow.html.erb
<%if user != current_user %>
	<%if current_user.following?(user)%>
		<%= link_to 'Unfollow', followship_path(user), method: :delete, class: "btn btn-outline-light"%>
	<%else%>
		<%= link_to 'Follow', followships_path(following_id: user), method: :post, class: "btn btn-outline-light" %>
	<%end%>	    
<%end%>

app/views/shared/_friend.html.erb
<%if current_user != user%>
  	<%if current_user.friend_of?(user)%>
  		<%= link_to "Unfriend", friendship_path(id: user), method: :delete, class: "btn btn-outline-light"%>
  	<%else%>	
  		<%= link_to "Friend", friendships_path(friend_id: user), method: :post, class: "btn btn-outline-light"%>
  	<%end%>
<%end%>

app/views/shared/_like.html.erb
<% if not restaurant.is_liked?(current_user)%>
	<%= link_to like_restaurant_path(restaurant), method: :post, :id => "like-star", :class => "btn btn-outline-primary" do %>
		<span class="glyphicon glyphicon-star-empty"></span>
	<%end%>
<%else%>
	<%= link_to unlike_restaurant_path(restaurant), method: :delete, :id => "like-star", :class => "btn btn-outline-primary" do%>
		<span class="glyphicon glyphicon-star"></span>
	<%end%>
<%end%>

app/views/shared/_navbar.html.erb
<ul class="nav nav-tabs nav-justified">
	
	<li role="presentation" class="<%= current_nav_page?(root_path)%>"><%= link_to '首頁', root_path %></li>
	<li role="presentation" class="<%= current_nav_page?(feeds_restaurants_path)%>"><%= link_to '最新動態', feeds_restaurants_path %></li>
	<li role="presentation" class="<%= current_nav_page?(ranking_restaurants_path)%>"><%= link_to 'Top10餐廳', ranking_restaurants_path %></li>
	<li role="presentation" class="<%= current_nav_page?(users_path)%>"><%= link_to '美食達人', users_path%></li>
</ul>

app/views/shared/_restaurant_list.html.erb
<div class="row">
<% @restaurants.each do |restaurant|%>
	<div class="col-sm-6 col-md-4">
		<div class="restaurant-item">
			<%#= image_tag restaurant.image %>
			<!--the image tag below is for testing purpose only. User the restaurant.image when S3 is coorectly configured to Heroku-->
			<%= image_tag "/fake_images/restaurants/00#{rand(0..9)}.jpg" %>
			<div class="caption">
				<h3 id="restaurant-label"><%= link_to restaurant.name, restaurant_path(restaurant)%></h3>
				<p class="label label-default"><%= restaurant.category_name %></p>
				<%= render partial: "shared/favourite.html.erb", locals: {restaurant: restaurant}%>
				<%= render partial: "shared/like.html.erb", locals: {restaurant: restaurant}%>
				<p><%= truncate(restaurant.description, length: 60)%></p>
			</div>
		</div>		
	</div>
<%end%>
	<div class="col-sm-12 text-center">
		<%= paginate @restaurants%>
	</div>
</div>